name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v4

    - name : Install Packages
      run : |
        python3 -m pip install flask
        python3 -m pip install requests
        python3 -m pip install pytest

    - name : Run tests
      run : pytest -v -s

